name: Build and Release

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-musl
            arch: aarch64
          - target: x86_64-unknown-linux-musl
            arch: x86_64
    
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Toolchain"
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
          override: true

      - name: Install MUSL linker (musl-tools)
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Build (release) for ${{ matrix.target }}
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Upload build artifact
        run: |
          mv target/${{ matrix.target }}/release/jellyfin-discovery-util ./${{ matrix.arch }}-jellyfin-discovery-util
          gh release upload ${{github.event.release.tag_name}} ${{ matrix.arch }}-jellyfin-discovery-util
